resolver: lts-13.5

packages:
- '.'

extra-deps:
- haskus-utils-1.4
- haskus-utils-data-1.1.1
  # - haskus-utils-types-1.3.1
- git: http://github.com/haskus/haskus-utils
  commit: 40a6d7704239996a6c394fbda507990ab28a06d5
  subdirs:
      - haskus-utils-types
      
- haskus-utils-variant-2.5
- stm-containers-1.1.0.2
- stm-hamt-1.2.0.2
- primitive-extras-0.7.1

ghc-options:
   "$locals": -fhide-source-paths -freverse-errors
