resolver: lts-13.5

packages:
- '.'

ghc-options:
   "$locals": -fhide-source-paths

extra-deps:
- happstack-server-tls-7.1.6.7
- happstack-server-7.5.1.3
- haskus-binary-1.3
- haskus-utils-1.4
- haskus-utils-data-1.1.1
- haskus-utils-types-1.3.1
- haskus-utils-variant-2.5
- haskus-utils-compat-1.0
- stm-containers-1.1.0.2
- stm-hamt-1.2.0.2
- primitive-extras-0.7.1
