resolver: lts-13.16

packages:
- haskus-utils-compat/
- haskus-utils/
- haskus-utils-types/
- haskus-utils-data/
- haskus-utils-variant/
- haskus-binary/
- haskus-web/
- haskus-format-text/
- haskus-locale/
- haskus-calculus/
- haskus-graphics/

extra-deps:
- stm-containers-1.1.0.2
- stm-hamt-1.2.0.2
- primitive-extras-0.7.1
- happstack-server-tls-7.1.6.7
- happstack-server-7.5.1.3

ghc-options:
   "$locals": -fhide-source-paths -freverse-errors

build:
   interleaved-output: true
