resolver: https://raw.githubusercontent.com/haskus/haskus-snapshots/c4e1ccf13fc397de50905c94c7b4eda249eba23c/haskus-0.yaml

packages:
- '.'

extra-deps:
- '../haskus-utils-types'
- '../haskus-utils-data'
- '../haskus-utils-variant'

ghc-options:
   "$locals": -fhide-source-paths
