name:                haskus-integer
version:             0.1
github:              "haskus/packages"
license:             BSD3
author:              "Sylvain HENRY"
maintainer:          "sylvain@haskus.fr"
copyright:           "Sylvain HENRY 2019"

description:         Please see the README on Github at <https://github.com/haskus/packages/#readme>

dependencies:
- base >= 4.8 && < 5

ghc-options: -Wall -O -fobject-code

library:
   source-dirs: src/lib
   exposed-modules:
      - Haskus.Number.BigNat
      - Haskus.Number.Natural
      - Haskus.Number.Integer
   dependencies:
      - base >= 4.8 && < 5

tests:
   main-tests:
      main: Main.hs
      source-dirs: src/tests
      dependencies:
         - haskus-integer
         - tasty
         - tasty-quickcheck
